[master]
master1 ansible_ssh_host=1.2.3.101 ansible_host=1.2.3.101
master2 ansible_ssh_host=1.2.3.102 ansible_host=1.2.3.102
master3 ansible_ssh_host=1.2.3.103 ansible_host=1.2.3.103


[worker]
worker1 ansible_ssh_host=1.2.3.111 ansible_host=1.2.3.111
worker2 ansible_ssh_host=1.2.3.112 ansible_host=1.2.3.112
#worker3 ansible_ssh_host=1.2.3.113 ansible_host=1.2.3.113

[etcd]
etcd1 ansible_ssh_host=1.2.3.201 ansible_host=1.2.3.201
etcd2 ansible_ssh_host=1.2.3.202 ansible_host=1.2.3.202
etcd3 ansible_ssh_host=1.2.3.203 ansible_host=1.2.3.203

[k8s:children]
master
worker

[k8s:vars]
etcd_mode=external
kube_vip_address=1.2.3.187
kube_vip_port=6443
kube_vip_interface=eth0
kube_pod_cidr=10.244.0.0/16
ansible_user=user
ansible_password='password'
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

[etcd:vars]
# This directory is on the Ansible controller (CentOS or Ubuntu are both supported).
etcd_cert_work_dir=/tmp/k8s-etcd-certs
etcd_cert_file=/etc/etcd/pki/cluster.pem
etcd_key_file=/etc/etcd/pki/cluster.key
etcd_trusted_ca_file=/etc/etcd/pki/ca.pem
ansible_user=user
ansible_password='password'
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
